name: UnixSocketTest
version: ${project.version}
main: org.betterbox.unixSocketTest.UnixSocketTest
api-version: '1.18'
load: STARTUP
authors: [ Grzybol ]
description: Minecraft Velocity login plugin
softdepend:
  - ElasticBuffer
commands:
    ust:
        description: Main command for UnixSocketTest.
        usage: /ust <reloadconfig|spawnnpc>
        permission: unixSocketTest.admin
        permission-message: You do not have permission to use this command.
